name: GitHub Action Start
on: [push]
jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is automatically triggered job by a ${{ github.event_name }}"
      - run: echo "OS is ${{ runner.os }}"
      - run: echo "URL is ${{ vars.URL }}"